# Hyperliquid Trade Execution Bot (trade.py)
#
# This script reads the 'trade_signals.json' file generated by the dashboard.
# If it detects a 'buy_signal', it executes a market buy order, logs the trade,
# and then resets the signal in the JSON file to prevent duplicate trades.
#
# To Run:
# 1. Ensure 'collector.py' and 'app.py' are running.
# 2. Configure your trade size in the 'TRADE_USD_SIZE' variable below.
# 3. Run this script from your terminal: python trade.py

import example_utils
from hyperliquid.utils import constants
import time
import json
import os
from datetime import datetime

# --- Configuration ---
SIGNAL_FILE = "trade_signals.json"
TRADE_LOG_FILE = "trade_log.json" # Corrected filename
CHECK_INTERVAL_SECONDS = 5  # Check the signal file every 5 seconds
TRADE_USD_SIZE = 225 # The size of the trade to place in USD

def read_signal_file():
    """Reads the signal data from the JSON file."""
    if not os.path.exists(SIGNAL_FILE):
        return None
    try:
        with open(SIGNAL_FILE, 'r') as f:
            return json.load(f)
    except (json.JSONDecodeError, FileNotFoundError):
        # Handle cases where the file is empty or being written to
        return None

def reset_signal_file(data):
    """Resets the buy_signal and trigger_on to false in the JSON file."""
    print("[*] Resetting signal file to prevent duplicate trades...")
    data['state']['buy_signal'] = False
    data['state']['trigger_on'] = False
    with open(SIGNAL_FILE, 'w') as f:
        json.dump(data, f, indent=4)
    print("[*] Signal file has been reset.")

# --- MODIFIED: Function to log trade details with trade_type ---
def log_trade(signal_data, order_result, order_size, trade_type):
    """Appends the details of a trade attempt to the trade log file."""
    print(f"[*] Logging '{trade_type}' trade attempt...")
    log_entry = {
        "log_timestamp": datetime.now().isoformat(),
        "trade_type": trade_type, # <-- NEW: Added trade type to the log
        "trade_size_usd": TRADE_USD_SIZE,
        "calculated_asset_size": order_size,
        "signal_data": signal_data,
        "exchange_response": order_result
    }
    
    # Read existing log data and append the new entry
    try:
        if os.path.exists(TRADE_LOG_FILE):
            with open(TRADE_LOG_FILE, 'r') as f:
                logs = json.load(f)
        else:
            logs = []
    except json.JSONDecodeError:
        logs = []

    logs.append(log_entry)

    # Write the updated log back to the file
    with open(TRADE_LOG_FILE, 'w') as f:
        json.dump(logs, f, indent=4)
    print("[*] Trade logged successfully.")

def main():
    """
    Main loop to check for signals and execute trades.
    """
    print("--- Hyperliquid Trading Bot ---")
    print("[*] Setting up connection...")
    
    # Setup connection to Hyperliquid
    address, info, exchange = example_utils.setup(constants.MAINNET_API_URL, skip_ws=True)
    print(f"[*] Successfully set up trading for address: {address}")
    print("[*] Bot is running. Waiting for a buy signal...")
    print("-" * 30)

    while True:
        try:
            # 1. Read the signal file
            signal_data = read_signal_file()

            if signal_data and signal_data.get('state', {}).get('buy_signal'):
                print(f"\n[!] BUY SIGNAL DETECTED at {signal_data.get('timestamp')}")
                print(f"    Price: ${signal_data.get('latest_price', 0):.2f}, Fib 0: ${signal_data.get('fib_0_level', 0):.2f}")

                # --- Execute The Trade ---
                coin = signal_data['coin']
                is_buy = True
                trade_type = "buy" # Define the trade type

                meta = info.meta()
                sz_decimals = next((asset["szDecimals"] for asset in meta["universe"] if asset["name"] == coin), 2)

                market_price = float(info.all_mids()[coin])
                order_size_in_asset = round(TRADE_USD_SIZE / market_price, sz_decimals)
                
                print(f"[*] Placing market buy order for {order_size_in_asset} {coin}...")
                
                order_result = exchange.market_open(coin, is_buy, order_size_in_asset, None, 0.01)

                print("[*] Trade Result:")
                print(order_result)
                
                # 2. Log the trade attempt
                # MODIFIED: Pass the trade_type to the log_trade function
                log_trade(signal_data, order_result, order_size_in_asset, trade_type)
                
                # 3. Reset the signal file if the order was accepted by the exchange
                if order_result.get("status") == "ok":
                    reset_signal_file(signal_data)
                else:
                    print("[!] ERROR: Order failed. Signal file will not be reset.")

                print("\n[*] Waiting for next signal...")

            time.sleep(CHECK_INTERVAL_SECONDS)

        except KeyboardInterrupt:
            print("\n[*] Bot stopped by user. Goodbye!")
            break
        except Exception as e:
            print(f"[!] An error occurred: {e}")
            time.sleep(CHECK_INTERVAL_SECONDS * 2)

if __name__ == "__main__":
    main()
